frameLength = 512;
fileReader = dsp.AudioFileReader(...
    'CARRIER.wav',...
    'SamplesPerFrame',frameLength);
deviceWriter = dsp.audioDeviceWriter(...
    'SampleRate',fileReader.SampleRate,...
    'TimeSpan',16, ...
    'BufferLength',1.5e6,...
    'YLimits',[-1 1]);
